#%RAML 1.0 NamedExample
[
    {
      "id":37,
      "first":"John",
      "last":"Mike",
      "department":"DevOps"
    },
    {
      "id":38,
      "first":"Mary",
      "last":"Alem",
      "department":"MuleSoft"
    }
]